import { IDataCard } from "../interfaces/interfaces";

export const data: Array<IDataCard> = [
  {
    name: 'Vintage Belt - Red',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'belt',
    color: 'black',
    price: '110',
    stock: '2',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: true,
    freeShipping: false,
    manufacturer: 'other',
    amount: 1,
    year: 2021,
  },
  {
    name: 'wallet red',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'wallet',
    color: 'red',
    price: '110',
    stock: '5',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: true,
    freeShipping: true,
    manufacturer: 'alPaco',
  },
  {
    name: 'Vintage Belt - Red',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'bag',
    color: 'gold',
    price: '110',
    stock: '3',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: false,
    freeShipping: false,
    manufacturer: 'other',
  },
  {
    name: 'Vintage Belt - Red',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'belt',
    color: 'red',
    price: '110',
    stock: '0',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: false,
    freeShipping: false,
    manufacturer: 'alPaco',
  },
  {
    name: 'brown belt',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'belt',
    color: 'brown',
    price: '110',
    stock: '22',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: true,
    freeShipping: true,
    manufacturer: 'alPaco',
  },
  {
    name: 'documents',
    img: './assets/img/belt_red_vintage.jpg',
    type: 'forDocuments',
    color: 'brown',
    price: '110',
    stock: '0',
    description:
      'Red vintage belt. Natural leather, strong furniture. Leather thickness - 4-4.2 mm',
    productionTime: '2',
    bestseller: true,
    freeShipping: true,
    manufacturer: 'alPaco',
  },
];